# Nombre: Vicente Fernández M.

### Ejercicio 2 - Generando números binarios

Se le pide que escriba las instrucciones de la función ``genera_binarios`` de acuerdo al siguiente algoritmo:

---



* si el valor de ``k`` es igual a ``n``, ya se han generado todos los dígitos por
    lo cual se imprime el arreglo en pantalla ``(print(a))``
* si no, se hacen dos cosas:  
    - se pone un 0 en la ``k``-ésima posicion y se llama recursivamente
      a la función para que genere los dígitos restantes
    - luego se pone un 1 en la misma ``k``-ésima posición (reemplazando el 0) y se
      llama recursivamente a la función para que genere los dígitos restantes

Pruebe su función con para el caso ``n=4``. Asegúrese de que genere el mismo resultado que el que aparece en el enunciado.


In [ ]:
def genera_binarios(a,k,n):
    if k == n:                                                                  # Caso base: k-n = 0, no faltan digitos
        print(a)                                                                # se imprime el arreglo generado en pantalla
    else:
        a[k] = 0                                                                # k comienza en 0 y debe llegar hasta n (lo que se pide)
        genera_binarios(a,k+1,n)                                                # asi, en cada iteracion se aumenta el nro k para impimir mas numeros.

        a[k] = 1
        genera_binarios(a,k+1,n)

In [25]:
import numpy as np
n = 4                                                                       
a = np.empty(n,dtype=int)                                                       # Arreglo vacío de tamaño 'n', se llena dsp
genera_binarios(a,0,len(a))

[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[0 1 1 0]
[0 1 1 1]
[1 0 0 0]
[1 0 0 1]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]
