# CC3001 Otoño 2026 Tarea 2: Vicente Fernández M.

## Shellsort

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos un arreglo "$d$-ordenado" (donde $d$ es un entero mayor o igual a 1) como un arreglo en que cada elemento está ordenado respecto de sus vecinos que están a $d$ casilleros de distancia. Por ejemplo, en el siguiente diagrama se muestran un arreglo antes y después de ser "3-ordenado", destacando en distintos colores las subsecuencias que se forman al considerar elementos que están a distancia 3:

Antes:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Después:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Noten que el caso particular de un arreglo "1-ordenado" (caso $d=1$) sería lo mismo que un arreglo ordenado.

El algoritmo Shellsort consiste en hacer una secuencia de pasadas $d$-ordenando el arreglo, cada vez con un valor diferente de $d$, siendo la última siempre con $d=1$.

Para hacer una pasada de Shellsort elegimos un valor de $d$ y luego aplicamos una versión modificada de ordenación por inserción. La modificación consiste en que la función ``insertar(a,k)`` compara con el elemento $d$ casilleros más atrás, en lugar de hacerlo con el que está uno más atrás.

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_i,d_{i-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [34]:
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):                                                        # para cada elem k-esimo en la lista:
        insertar(a,k)                                                               # aplicar insercion

def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k]                                                                      # se 'saca' el elem a analizar
    j=k                                                                         # guardar la posición del lugar "vacío"

    while j>0 and b<a[j-1]:                                                     # empieza del final y k-esimo sea menor q anterior
        a[j]=a[j-1]                                                                 # pasar el anterior a k
        j-=1                                                                        # pasar al anterior
    a[j]=b                                                                      # el guardado pasa al j nuevo (si se hizo cambio j es el mismo, si no cambio al anterior)

Probemos esto para asegurarnos que funcione bien:

In [35]:
import numpy as np

def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print("Arreglo "+str(d)+"-ordenado OK.")

A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar una $d$-ordenación

Modifique el código anterior para que $d$-ordene el arreglo, para un valor de $d$ dado. Para esto, escriba el código de la función ``d_insertar`` en el espacio provisto:

d-ordenar arreglo: 
ordenar los nros a una distancia d
    comenza en uno
    procesar cada d
    

In [24]:
import numpy as np

def d_ordena_insercion(a,d):
    """d-Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        d_insertar(a,k,d)
        print(a)
        
def d_insertar(a,k,d):
    """
    Inserta a[k] entre los elementos anteriores a distancia d
    preservando el orden ascendente (versión 2)
    """

    b = a[k]                                                                    # se 'saca' el elem a analizar
    j = k                                                                       # guardar la posición del lugar "vacío"

    ## algoritmo princ: ##
    # comparar elem con el anterior d-espacios atras e intercambiar si es menor:
    while (j > 0 and b < a[j - d]):

        a[j] = a[j - d]                                                         # intercambia el sig a ser ordenado con el de d-atras
        j = j - d                                                               # disminuir j segun 'd' para pasar a analizarlo

    a[j] = b

Pruebe aquí que su algoritmo $3$-ordena correctamente:

In [25]:
import numpy as np

def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print("Arreglo "+str(d)+"-ordenado OK.")
    
A = np.array([46,35,95,21,82,70,72,56,64,50])
d_ordena_insercion(A,3)
print(A)
verifica_d_ordenado(A,3)

[46 35 95 21 82 70 72 56 64 50]
[46 64 95 21 82 70 72 56 35 50]
[46 64 95 21 82 70 72 56 35 50]
[21 64 95 46 82 70 72 56 35 50]
[21 64 95 46 82 70 72 56 35 50]
[21 64 70 46 82 95 72 56 35 50]
[21 64 70 46 82 95 72 56 35 50]
[21 56 70 46 64 95 72 82 35 50]
[21 56 50 46 64 70 72 82 95 35]
[21 56 50 35 64 70 46 82 95 72]
[21 56 50 35 64 70 46 82 95 72]
Arreglo 3-ordenado OK.


## 2) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_i=2^i+1$ para $i\ge 1$, y terminando con un $1$. Esto es: $\ldots, 65, 33, 17, 9, 5, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$. Su programa debe partir con el índice $i$ más grande tal que $d_i<n$.

In [26]:
import numpy as np

def Shellsort(a):
    """Ordena a usando Shell Sort, con la secuencia de valores …,65,33,17,9,5,3,1"""

    n=len(a)

    # se va a generar una lista con los d validos, tq: 2**i + 1 < n
    lista_d = [1]

    i = 1
    while ( (2**i) + 1 < n ):                                                   # se llena lista hasta antes de superar n
        lista_d.insert( 0, (2**i)+1)
        i += 1
        print('lista d:', lista_d)

    # para todos los elementos, se d-ordena y por cada pasada, se usa un menor d
    for d in lista_d:
        for k in range(0,n):                                                    # con el mismo d, se d-ordena la lista
        
            b = a[k]                                                                # se 'saca' el elem a analizar
            j = k                                                                   # guardar la posición del lugar "vacío"

            while (j > 0 and b < a[j - d]):                  # Compara jesimo con jesimo-d
                
                a[j] = a[j - d]                                            # intercambia el sig a ser ordenado con el de d-atras
                j = j - d                                                  # disminuir j segun 'd' para pasar a analizarlo

            a[j] = b

Pruebe aquí su algoritmo de la manera siguiente:

In [27]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
print(A)
Shellsort(A)
print(A)
verifica_d_ordenado(A,1)

[46 35 95 21 82 70 72 56 64 50]
lista d: [3, 1]
lista d: [5, 3, 1]
lista d: [9, 5, 3, 1]
[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

In [77]:
import numpy as np
from numpy import random

A_random = np.random.randint(0, 10000, size=1000)

Shellsort(A_random)
verifica_d_ordenado(A,1)

Arreglo 1-ordenado OK.


## 3) Probar con una secuencia diferente de valores $d_i$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_i$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

La propuesta original de Shell [1] es con:
$$
\lfloor{\frac{N}{2^{k}}} \rfloor
$$
que tiene complejidad $\Theta(n^2)$. No es tan efectivo, pero es la primera implementación del algoritmo.

[1] Shell, D. L. (1959). A high-speed sorting procedure. Communications of the ACM, 2(7), 30–32. https://doi.org/10.1145/368370.368387

In [ ]:
import numpy as np
import math

def Shellsort_2(a):

    n=len(a)

    # se va a generar una lista con los d validos
    lista_d = [1]

    i = 1
    while ( math.floor(n / 2**i) < n ):                                                   # se llena lista con los d validos

        lista_d.append(math.floor(n / 2**i))
        i += 1

        if ( lista_d[i-1] == 0 ):
            break

    # para todos los elementos, se d-ordena y por cada pasada, se usa un menor d
    for d in lista_d:
        for k in range(0,n):                                                    # con el mismo d, se d-ordena la lista
        
            b = a[k]                                                                # se 'saca' el elem a analizar
            j = k                                                                   # guardar la posición del lugar "vacío"

            while (j > 0 and b < a[j - d]):                  # Compara jesimo con jesimo-d
                
                a[j] = a[j - d]                                            # intercambia el sig a ser ordenado con el de d-atras
                j = j - d                                                  # disminuir j segun 'd' para pasar a analizarlo

            a[j] = b

ahora probar:

In [ ]:
import numpy as np
from numpy import random

A_random = np.random.randint(0, 100, size=20)

Shellsort_2(A_random)

print(A_random)
verifica_d_ordenado(A,1)

[ 3  3  5  5  6 16 28 28 41 50 50 54 67 73 73 79 82 82 92 94]
Arreglo 1-ordenado OK.
